services:

  postgis:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
